# Generated by Django 4.1.13 on 2024-10-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Authors",
                    models.CharField(default="Unknown Authors", max_length=5000),
                ),
                ("Authors_full_names", models.TextField(default="Unknown Authors")),
                ("Author_ID", models.CharField(default="Unknown", max_length=1000)),
                ("Title", models.CharField(default="Unknown Title", max_length=1000)),
                ("Year", models.CharField(default="0000", max_length=5)),
                (
                    "Source_title",
                    models.CharField(default="Unknown Source", max_length=1000),
                ),
                ("Volume", models.CharField(default="N/A", max_length=50)),
                ("Issue", models.CharField(default="N/A", max_length=50)),
                ("Art_No", models.CharField(blank=True, max_length=50, null=True)),
                ("Page_start", models.CharField(default="N/A", max_length=10)),
                ("Page_end", models.CharField(default="N/A", max_length=10)),
                ("Page_count", models.CharField(max_length=10)),
                ("Citations", models.CharField(blank=True, max_length=2, null=True)),
                ("DOI", models.CharField(blank=True, max_length=100, null=True)),
                ("Link", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "Affiliations",
                    models.CharField(default="Unknown Affiliations", max_length=500),
                ),
                ("Authors_with_Affiliations", models.TextField(blank=True, null=True)),
                ("Abstract", models.TextField(blank=True, null=True)),
                ("Author_Keywords", models.TextField(blank=True, null=True)),
                ("Index_Keywords", models.TextField(blank=True, null=True)),
                (
                    "Molecular_Sequence_Numbers",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("Chemicals", models.TextField(blank=True, null=True)),
                ("Tradenames", models.TextField(blank=True, null=True)),
                ("Manufacturers", models.TextField(blank=True, null=True)),
                ("Funding_Details", models.TextField(blank=True, null=True)),
                ("Funding_Texts", models.TextField(blank=True, null=True)),
                ("Reference", models.TextField(blank=True, null=True)),
                ("Correspondence_Address", models.TextField(blank=True, null=True)),
                ("Editors", models.TextField(blank=True, null=True)),
                (
                    "Publisher",
                    models.CharField(default="Unknown Publisher", max_length=500),
                ),
                ("Sponsors", models.TextField(blank=True, null=True)),
                (
                    "Conference_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Conference_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Conference_location",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Conference_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ISSN", models.CharField(blank=True, max_length=50, null=True)),
                ("ISBN", models.CharField(blank=True, max_length=50, null=True)),
                ("CODEN", models.CharField(blank=True, max_length=50, null=True)),
                ("PubMed_ID", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Language",
                    models.CharField(default="Unknown Language", max_length=500),
                ),
                (
                    "Abbreviated_Source_Title",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("Document", models.CharField(default="null", max_length=500)),
                (
                    "Publication_Stage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Open_Access", models.CharField(default=False, max_length=100)),
                ("Source", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
