# Generated by Django 4.2.17 on 2025-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_name", "0002_alter_paperrank_abbreviated_source_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperrank",
            name="EID",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="paperrank",
            name="Author_ID",
            field=models.CharField(
                default="Unknown", max_length=2000, verbose_name="Author ID"
            ),
        ),
    ]
